### PR TITLE
fix: visitor bindingtarget empty target

### PR DESCRIPTION
**Pull request by robin-samuel**

### CODE REVIEW

**Review by T14Raptor — CHANGES_REQUESTED** [review]
Thanks for the PR, but `visit.go` is generated in `gen_visit.go`. Please add a `optional:"true"` struct tag to the field then generate `visit.go` by running `go run ast/gen_visit.go`, thank you

**Comment by toman-tom** [comment]
@T14Raptor we should implement the GitHub action we discussed in Discord to do this automatically

**Comment by robin-samuel** [comment]
@T14Raptor done

**Comment by robin-samuel** [comment]
@T14Raptor parser should work now with empty catch parameter
```js
try {
    var a = 1;
} catch {
    console.log("Error");
}
```

**Review by T14Raptor — APPROVED** [review]

**Pull request merged**
