### PR TITLE
Scope resolver

### PR DESCRIPTION
**Pull request by T14Raptor**

### CODE REVIEW

**Comment by toman-tom** [comment]
@T14Raptor  this looks good. Tested on a few projects and seems okay, anything further to add before merge?

**Comment by T14Raptor** [comment]
I think the only thing left is to handle arrow functions

**Comment by toman-tom** [comment]
Do you want to add it as a `feat` for now, or will you handle arrow funcs before merge?

**Comment by T14Raptor** [comment]
@toman-tom squash and merge when you're ready

**Comment by T14Raptor** [comment]
Actually don't merge this yet, running into some issues

**Pull request merged**
